export const projects = [
  {
    title: "MacTA",
    description: [
      "MacTA is command-line application that utilizes the OpenAI API to generate instructions for performing tasks in the MacOS terminal. The purpose of this application is to generate clear and concise instructions without having to leave the terminal. This can be particularly helpful for individuals who are new to the terminal or unfamiliar with specific terminal commands.",
    ],
    image: "",
    alt: "",
    code: "https://github.com/damonpickett/macta",
    site: "https://www.npmjs.com/package/macta",
    stack: "JavaScript, OpenAI API",
    id: 0,
  },
  {
    title: "buge",
    description: [
      "buge is a command-line application that helps developers understand and troubleshoot common error messages by generating explanations and solutions using the OpenAI GPT-3 language model.",
    ],
    image: "",
    alt: "",
    code: "https://github.com/damonpickett/buge",
    site: "https://pypi.org/project/buge/",
    stack: "Python, OpenAI API",
    id: 1,
  },
  {
    title: "Black Brook Lodge",
    description: [
      "Black Brook Lodge is an events centre in Qualicum Beach, BC. I built this site in Wordpress for a client who wanted to drive more traffic to his AirBnB listing. Since building this site Black Brook Lodge is now receiving regular bookings.",
    ],
    image: "",
    alt: "",
    code: "",
    site: "https://blackbrooklodge.ca/",
    stack: "Wordpress, Elementor",
    id: 2,
  },
  {
    title: "Sea Weasel",
    description: [
      "Sea Weasel is a punk rock, nautical clothing line. This landing page collects users' emails who want to be notified of product releases.",

    ],
    image: "",
    alt: "",
    code: "https://github.com/sea-weasel/sea-weasel.github.io",
    site: "https://seaweasel.ca/",
    stack: "React.js, Mailchimp",
    id: 3,
  },
  {
    title: "Torbomb Design",
    description: [
      "Torbomb Designs is expanding possibilities in the world of paintball by creating accessories via 3D printing technology. I built this online store site to help my client sell his creations online.",
      
    ],
    image: "",
    alt: "",
    code: "",
    site: "https://torbombdesigns.bigcartel.com/",
    stack: "Big Cartel",
    id: 4,
  },
  {
    title: "The Whitsteen Project",
    description: [
      "The Whitsteen Project is a mock NFT art project featuring the work of Whitsteen. I built this site to demonstrate my ability to conceptualize and execute an NFT art project. Users are able to connect their Ethereum wallets and purchase NFTs. Using OpenZeppelin's `PaymentSplitter.sol` l contract I created a `payments.sol` contract which allows me to designate addresses that are eligible to withdraw revenue generated by the site.",
      
    ],
    image: "",
    alt: "",
    code: "https://github.com/damonpickett/whitsteen-project",
    site: "https://damonpickett.github.io/whitsteen-project/",
    stack: "React, Solidity, Hardhat, Ethers.js",
    id: 5,
  },
  
];
